### PR TITLE
support thoth-station prod integration test application via argocd

### PR DESCRIPTION
**Pull request by harshad16**
## This Pull Request implements

support thoth-station prod integration test application via argocd
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

## If migrating an Application to ArgoCD
- [x] I have completed the list of action items on [this page](https://aicoe.github.io/aicoe-cd/get_argocd_to_manage_your_app/)

### CODE REVIEW

**Comment by anishasthana** [comment]
commit  message has a typo, could you fix that?

**Comment by harshad16** [comment]
> commit message has a typo, could you fix that?

oh sure
do we have to maintain the correct commit message as well ? (just asking for personal knowledge)

**Comment by HumairAK** [comment]
Did you intend to include this in the `kustomization.yaml` or no?

**Comment by harshad16** [comment]
> Did you intend to include this in the `kustomization.yaml` or no?

thanks for pointing that out, I completely forgot :+1:

**Review by anishasthana — APPROVED** [review]

**Review by HumairAK — APPROVED** [review]

**Pull request merged**
