### PR TITLE
Add data-catalog namespace for ArgoCD to manange

### PR DESCRIPTION
**Pull request by maulikjs**
## This Pull Request implements

This PR adds data-catalog namespaces to be managed by argocd in prod and stage.
It also adds the application manifests for the same.

## If migrating an Application to ArgoCD
- [x] I have completed the list of action items on [this page](https://aicoe.github.io/aicoe-cd/get_argocd_to_manage_your_app/)

### CODE REVIEW

**Comment by HumairAK** [comment]
does the argocd-manager have admin access to these namespaces for each cluster?

**Comment by maulikjs** [comment]
Yeah thats included in this MR: 
https://github.com/AICoE/idh-manifests/pull/39/files

**Comment by HumairAK** [comment]
okay, the namespaces being added here should have that rolebinding deployed before this one is merged

**Comment by maulikjs** [comment]
Yup, I have already applied those to their respective namespaces.

**Review by HumairAK — APPROVED** [review]

**Review by accorvin — APPROVED** [review]
🚢

**Review by anishasthana — APPROVED** [review]

**Review by tumido — APPROVED** [review]

**Pull request merged**
