### PR TITLE
change the deployment namespace for thoth task

### PR DESCRIPTION
**Pull request by harshad16**
## This Pull Request implements

change the deployment namespace for thoth task
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Comment by anishasthana** [comment]
Thanks @harshad16 . Can you confirm for me that ArgoCD has access to this namespace?

**Comment by harshad16** [comment]
> Can you confirm for me that ArgoCD has access to this namespace?

yes @anishasthana , it has the access :+1:

**Review by anishasthana — COMMENTED** [review]
/lgtm

**Review by anishasthana — APPROVED** [review]

**Pull request merged**
