### PR TITLE
Remove dh-prod-customer-journeys app

### PR DESCRIPTION
**Pull request by gmfrasca**
## This Pull Request implements

Remove dh-prod-customer-journeys app

### CODE REVIEW

**Comment by maulikjs** [comment]
You also need to remove the reference to the file here: manifests/overlays/prod/applications/data_hub/kustomization.yaml

**Review by accorvin — APPROVED** [review]

**Comment by anishasthana** [comment]
Can you rebase on master? @gmfrasca

**Review by maulikjs — APPROVED** [review]

**Pull request merged**
