### PR TITLE
Add SrcOps token to access private repos

### PR DESCRIPTION
**Pull request by tumido**
## Related Issues

Required by #49 

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

In order to access private repos on GitHub, we to have Source Ops team member token available in secret in the ArgoCD namespace.

## Description

This PR adds Sesheta access token provided by @goern .

### CODE REVIEW

**Comment by HumairAK** [comment]
can we update the ansible password to use the proper one? otherwise lgtm

**Comment by tumido** [comment]
@HumairAK updated. Encrypted with the new password. Verified:

```
$ [ $(gopass AICoE/thoth/sesheta | grep -oP "(?<=SESHETA_GITHUB_SRCOPS_ACCESS_TOKEN=).*") == $(ansible localhost -m debug -a var="srcops_token" -e "@vars/common-vars.yaml" | grep -Po "(?<=srcops_token\": \").*(?=\")") ] && echo Password matches || echo Nope
Password matches
```

**Pull request merged**
