### PR TITLE
enable the purge job to be deployed

### PR DESCRIPTION
**Pull request by harshad16**
## This Pull Request implements

enable the purge job to be deployed
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

Related-to: https://github.com/thoth-station/thoth-application/pull/1208
## If migrating an Application to ArgoCD
- [x] I have completed the list of action items on [this page](https://aicoe.github.io/aicoe-cd/get_argocd_to_manage_your_app/)

### CODE REVIEW

**Comment by anishasthana** [comment]
@harshad16 shouldn't this have automatically assigned two reviewers?

**Comment by harshad16** [comment]
> shouldn't this have automatically assigned two reviewers?

interesting , will check

**Comment by harshad16** [comment]
couldnt find the reason for the ci not auto allocating reviewer
however didn't see issue on other pr's
may be this was a flake

**Review by anishasthana — COMMENTED** [review]
/lgtm

**Review by tumido — COMMENTED** [review]
/lgtm

**Review by anishasthana — APPROVED** [review]
/approve

**Pull request merged**
