### PR TITLE
Move Argocd applications to dedicated project

### PR DESCRIPTION
**Pull request by anishasthana**

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm

**Review by tumido — APPROVED** [review]

**Review by accorvin — APPROVED** [review]

**Comment by HumairAK** [comment]
you should add the rbac for this project so you can see it in the ui

**Comment by HumairAK** [comment]
I'm also not sure what the behavior for argocd will be when it tries to sync it's own app manifests and change projects -- so you should carefully monitor it during sync and manually deploy the projects / applications again if you need to.

**Comment by anishasthana** [comment]
Yep, I agree. I was wondering how we should do the update

**Pull request merged**
