### PR TITLE
feat(ccx): Add insights rules statistics app

### PR DESCRIPTION
**Pull request by tumido**
Depends on:
- https://github.com/AICoE/aicoe-cd/pull/189
- https://gitlab.cee.redhat.com/psilling/insights-rules-statistics/-/merge_requests/1

## This Pull Request implements

Adds CCX `insights-rules-statistics` application into CCX project.

## If migrating an Application to ArgoCD
- [x] I have completed the list of action items on [this page](https://aicoe.github.io/aicoe-cd/get_argocd_to_manage_your_app/)

### CODE REVIEW

**Comment by tumido** [comment]
/hold
until #189 is merged

**Review by anishasthana — APPROVED** [review]
:ship:

**Comment by anishasthana** [comment]
@tumido there's a merge conflict :(

**Comment by tumido** [comment]
@anishasthana naturally. :slightly_smiling_face:  fixed now. :+1:

**Review by anishasthana — APPROVED** [review]
lgtm

**Pull request merged**
