### PR TITLE
ignore the difference of image causing out-of-sync issue

### PR DESCRIPTION
**Pull request by harshad16**
## This Pull Request implements

ignore the difference of image causing out-of-sync issue
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

This is just a workaround, for now, to fix the out-sync issue and resource comsuption.
Related-to: https://github.com/thoth-station/thoth-application/issues/779

### CODE REVIEW

**Review by anishasthana — APPROVED** [review]
Thanks!

**Comment by tumido** [comment]
Any idea, why is this happening? Our Argo manifests for [aiops-prod-argo](https://github.com/AICoE/idh-manifests/tree/production/argo/overlays/aiops-prod-argo) are not having the same flaw..

**Comment by harshad16** [comment]
> Any idea, why is this happening? Our Argo manifests for [aiops-prod-argo](https://github.com/AICoE/idh-manifests/tree/production/argo/overlays/aiops-prod-argo) are not having the same flaw..

we are trying to investigate and debug on this, for that reason for time being just ignoring this so that it doesn't block any other apps from sync , because these apps are consuming all the resouces.

**Comment by HumairAK** [comment]
@martinpovolny  the ocp4 anomaly app is also included here, as it's also suffering the same problem. 

This basically causes apps to go in an infinite sync loop, which we suspect may be hogging other sync operations. We're continuing to debug this, but this will at least allow us to enable autosync on these apps.

**Review by HumairAK — APPROVED** [review]

**Comment by tumido** [comment]
@harshad16 sounds interesting.. It seems to be related to the `ImageStream` usage. When comparing your argo deployment and ours - the main difference is that we reference images directly from quay however you pull them into image streams instead. I wonder how does that behave when compared to the other image stream usage we do have...

**Comment by harshad16** [comment]
>  It seems to be related to the `ImageStream` usage. When comparing your argo deployment and ours - the main difference is that we reference images directly from quay however you pull them into image streams instead. I wonder how does that behave when compared to the other image stream usage we do have...

@tumido , this issue is very different I feel, as the same component doesn't seem to have the same issue in the other namespace.
what is happening is a deployment just contains the name of the image defined as per the manifest, when a pod is scheduled based on it, checks for the source and define that in the pod as per imagestream or external registry (based on manifest details).
however in this case openshift deployment component has changed the image to the absolute path of imagestream in place of the image, which shouldn't happen on deployment.

please do let me know your thought on this, would like to learn and understand if we are going wrong in any way.

**Pull request merged**
