### PR TITLE
Adjust path to manifests and add graph-metrics-exporter to test

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## This Pull Request implements

Adjust path that is in conflict with another application
Add graph-metrics-exporter to test for Thoth station

## If migrating an Application to ArgoCD
- [ ] I have completed the list of action items on [this page](https://aicoe.github.io/aicoe-cd/get_argocd_to_manage_your_app/)

### CODE REVIEW

**Comment by pacospace** [comment]
@tumido can we retest?

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
