### PR TITLE
Change prod superset to deploy from the new repo

### PR DESCRIPTION
**Pull request by rimolive**
## This Pull Request implements
Change prod superset to deploy from the new repo

## If migrating an Application to ArgoCD
- [x] I have completed the list of action items on [this page](https://aicoe.github.io/aicoe-cd/get_argocd_to_manage_your_app/)

### CODE REVIEW

**Comment by anishasthana** [comment]
Let's make sure to not accidentally merge this.

**Review by maulikjs — APPROVED** [review]

**Pull request merged**
