### PR TITLE
Enable auto-sync for all Data Hub applications

### PR DESCRIPTION
**Pull request by anishasthana**

### CODE REVIEW

**Review by rimolive — APPROVED** [review]

**Comment by anishasthana** [comment]
@HumairAK Do you feel comfortable with us enabling auto-sync for argocd apps again?

**Comment by HumairAK** [comment]
@anishasthana tbh I think this is a question more for you folks, if you feel confident in your merge / pr-review process then I'd say go for it.

**Comment by accorvin** [comment]
My opinion is that we should move the argocd and argocd-apps applications to their own project (not part of data hub project). That would signal that they are depended on by more than just the data hub team and that more reviewers should weigh in on changes.

**Comment by HumairAK** [comment]
@anishasthana -- I think I misunderstood the question, no don't turn on autosync for argocd-apps yet, it uses too much memory to sync, in the next argocd major release we'll be able to set it so that it only sync's "OOS" resources which will scale a lot better and reduce memory usage. Until then we want to keep auto sync off unfortunately.

**Review by HumairAK — APPROVED** [review]

**Review by accorvin — APPROVED** [review]

**Pull request merged**
