### PR TITLE
Add Kustomize Build Test Script

### PR DESCRIPTION
**Pull request by anishasthana**
This script was added for operate-first in https://github.com/operate-first/apps/pull/261

Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm

**Review by HumairAK — APPROVED** [review]

**Review by gmfrasca — APPROVED** [review]

**Review by anishasthana — COMMENTED** [review]
/lgtm

**Pull request merged**
